name: 001-008-cd2

on:
  push:
    branches: ["main"]
    paths:
      - "**/Tasks/001-008-cd2/**"
  pull_request:
    branches: ["main"]
    paths:
      - "**/Tasks/001-008-cd2/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Execute the step demo to verify that all is working
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      - name: Test Lab
        working-directory: Tasks/001-008-cd2
        run: bash ./_demo.sh
