name: 001-014-hidden-ls

on:
  push:
    branches: ["main"]
    paths:
      - "**/Tasks/001-014-hidden-ls/**"
  pull_request:
    branches: ["main"]
    paths:
      - "**/Tasks/001-014-hidden-ls/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Execute the step demo to verify that all is working
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      - name: Test Lab
        working-directory: Tasks/001-014-hidden-ls
        run: bash ./_demo.sh
