name: 001-006-passwd

on:
  push:
    branches: ["main"]
    paths:
      - "**/Tasks/001-006-passwd/**"
  pull_request:
    branches: ["main"]
    paths:
      - "**/Tasks/001-006-passwd/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Execute the step demo to verify that all is working
    steps:
      # Check out the code
      - uses: actions/checkout@v4

      - name: Test Lab
        working-directory: Tasks/001-006-passwd
        run: bash ./_demo.sh
